{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2013-08-21T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "lib/ansible/playbook/__init__.py in Ansible 1.2.x before 1.2.3, when playbook does not run due to an error, allows local users to overwrite arbitrary files via a symlink attack on a retry file with a predictable name in /var/tmp/ansible/."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2017-08-28T12:57:01",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://groups.google.com/forum/#%21topic/ansible-project/UVDYW0HGcNg"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=998227"
                },
                {
                    "name": "ansible-cve20134260-symlink(86898)",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_XF"
                    ],
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/86898"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "http://www.ansible.com/security"
                }
            ]
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "af854a3a-2127-422b-91ae-364da2661108",
                    "shortName": "CVE",
                    "dateUpdated": "2024-08-06T16:38:01.716Z"
                },
                "title": "CVE Program Container",
                "references": [
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_transferred"
                        ],
                        "url": "https://groups.google.com/forum/#%21topic/ansible-project/UVDYW0HGcNg"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_transferred"
                        ],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=998227"
                    },
                    {
                        "name": "ansible-cve20134260-symlink(86898)",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_XF",
                            "x_transferred"
                        ],
                        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/86898"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_transferred"
                        ],
                        "url": "http://www.ansible.com/security"
                    }
                ]
            }
        ]
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2013-4260",
        "datePublished": "2013-09-16T19:00:00",
        "dateReserved": "2013-06-12T00:00:00",
        "dateUpdated": "2024-08-06T16:38:01.716Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1"
}